UPDATE linli_codes SET tags='Animenz 紫罗兰永恒花园 Violet 动漫' WHERE id=186;
UPDATE linli_codes SET tags='轨迹系列 动漫' WHERE id=150;
UPDATE linli_codes SET tags='进击的巨人 V家' WHERE id=170;
UPDATE linli_codes SET tags='86不存在的战区 动漫' WHERE id=164;
UPDATE linli_codes SET tags='CLANNAD 动漫' WHERE id=196;
UPDATE linli_codes SET tags='战地风云 ACG' WHERE id=99;
UPDATE linli_codes SET tags='动漫' WHERE id=184;
UPDATE linli_codes SET tags='东方 V家' WHERE id=179;
UPDATE linli_codes SET tags='FF14 ACG' WHERE id=62;
UPDATE linli_codes SET tags='v家   初音未来 V家' WHERE id=240;
UPDATE linli_codes SET tags='初音未来 miku V家' WHERE id=200;
UPDATE linli_codes SET tags='恐怖 V家' WHERE id=202;
UPDATE linli_codes SET tags='V家' WHERE id=193;
UPDATE linli_codes SET tags='鸟之诗 AIR 动漫' WHERE id=168;
UPDATE linli_codes SET tags='Clannad 动漫' WHERE id=162;
UPDATE linli_codes SET tags='eva 动漫' WHERE id=163;
UPDATE linli_codes SET tags='崩铁 知更鸟 崩坏' WHERE id=108;
UPDATE linli_codes SET tags='崩铁 崩坏' WHERE id=11;
UPDATE linli_codes SET tags='崩铁 抒情 崩坏' WHERE id=188;
UPDATE linli_codes SET tags='ACG 寄生兽 动漫' WHERE id=76;
UPDATE linli_codes SET tags='动漫' WHERE id=194;
UPDATE linli_codes SET tags='动漫' WHERE id=182;
UPDATE linli_codes SET tags='紫罗兰永恒花园 动漫' WHERE id=172;
UPDATE linli_codes SET tags='CL 动漫' WHERE id=106;
UPDATE linli_codes SET tags='原神' WHERE id=102;
UPDATE linli_codes SET tags='EVA 动漫' WHERE id=79;
UPDATE linli_codes SET tags='崩铁 昔涟 崩坏' WHERE id=90;
UPDATE linli_codes SET tags='崩铁 崩坏' WHERE id=8;
UPDATE linli_codes SET tags='绝区零 崩坏' WHERE id=34;
UPDATE linli_codes SET tags='崩铁 崩坏' WHERE id=6;
UPDATE linli_codes SET tags='绝区零' WHERE id=35;
UPDATE linli_codes SET tags='绝区零' WHERE id=187;
UPDATE linli_codes SET tags='崩坏' WHERE id=178;
UPDATE linli_codes SET tags='东方 ACG' WHERE id=149;
UPDATE linli_codes SET tags='Saki酱 动漫' WHERE id=82;
UPDATE linli_codes SET tags='经典 动漫' WHERE id=7;
UPDATE linli_codes SET tags='游戏 原神' WHERE id=57;
UPDATE linli_codes SET tags='游戏 动漫' WHERE id=129;
UPDATE linli_codes SET tags='Animenz 紫罗兰永恒花园 动漫' WHERE id=117;
UPDATE linli_codes SET tags='Animenzzz 绝区零' WHERE id=32;
UPDATE linli_codes SET tags='Animenz 紫罗兰永恒花园 Violet 动漫' WHERE id=110;
UPDATE linli_codes SET tags='游戏 原神' WHERE id=19;
UPDATE linli_codes SET tags='东方 动漫' WHERE id=94;
UPDATE linli_codes SET tags='崩坏' WHERE id=135;
UPDATE linli_codes SET tags='fate 动漫' WHERE id=98;
UPDATE linli_codes SET tags='Animenzzz 绝区零' WHERE id=77;
UPDATE linli_codes SET tags='崩坏' WHERE id=52;
UPDATE linli_codes SET tags='游戏 ACG' WHERE id=126;
UPDATE linli_codes SET tags='崩铁 崩坏' WHERE id=59;
UPDATE linli_codes SET tags='绝区零 崩坏' WHERE id=142;
UPDATE linli_codes SET tags='流行 动漫' WHERE id=143;
UPDATE linli_codes SET tags='agc miku 初音未来 V家' WHERE id=159;
UPDATE linli_codes SET tags='崩坏' WHERE id=22;
UPDATE linli_codes SET tags='魔法少女小圆 动漫' WHERE id=115;
UPDATE linli_codes SET tags='我的世界 ACG' WHERE id=227;