UPDATE linli_codes SET tags='Roselia V家' WHERE id=180;
UPDATE linli_codes SET tags='去月球 动漫' WHERE id=169;
UPDATE linli_codes SET tags='末日时在做什么？有没有空？可以来拯救吗？ 动漫' WHERE id=189;
UPDATE linli_codes SET tags='动漫' WHERE id=158;
UPDATE linli_codes SET tags='凡人修仙传 ACG' WHERE id=165;
UPDATE linli_codes SET tags='V家' WHERE id=176;
UPDATE linli_codes SET tags='夏日口袋 ACG' WHERE id=177;
UPDATE linli_codes SET tags='坂本龙一 动漫' WHERE id=167;
UPDATE linli_codes SET tags='贝多芬 动漫' WHERE id=160;
UPDATE linli_codes SET tags='动漫' WHERE id=89;
UPDATE linli_codes SET tags='BLACKSOULS ACG' WHERE id=198;
UPDATE linli_codes SET tags='游戏 动漫' WHERE id=171;
UPDATE linli_codes SET tags='抒情 动漫' WHERE id=73;
UPDATE linli_codes SET tags='动漫' WHERE id=183;
UPDATE linli_codes SET tags='动漫' WHERE id=185;
UPDATE linli_codes SET tags='吉卜力 动漫' WHERE id=118;
UPDATE linli_codes SET tags='坂本龙一 动漫' WHERE id=153;
UPDATE linli_codes SET tags='游戏 ACG' WHERE id=136;
UPDATE linli_codes SET tags='动漫' WHERE id=156;
UPDATE linli_codes SET tags='天之少女 动漫' WHERE id=192;
UPDATE linli_codes SET tags='缘之空 动漫' WHERE id=116;
UPDATE linli_codes SET tags='游戏 ACG' WHERE id=4;
UPDATE linli_codes SET tags='原神' WHERE id=121;
UPDATE linli_codes SET tags='动漫' WHERE id=68;
UPDATE linli_codes SET tags='游戏 ACG' WHERE id=128;
UPDATE linli_codes SET tags='游戏 ACG' WHERE id=139;