INSERT INTO linli_codes (code, title, description, author, tags, status) VALUES
('HC63OU', '愤怒的小鸟bgm AngryBirds', '', '匿名', '游戏', 'approved'),
('GYJ97O', '有点甜', '汪苏泷', '匿名', '流行', 'approved'),
('PHPZE4', '崩铁 昔涟', '', '匿名', '崩铁', 'approved'),
('IAB4A8', '鸟之诗', '', '匿名', '经典', 'approved'),
('46Y97I', '崩铁 耀斑', '', '匿名', '崩铁', 'approved'),
('R6HOSD', 'One last kiss', '', '匿名', '动漫', 'approved'),
('MZGOUC', '夜的钢琴曲5', '', '匿名', '经典', 'approved'),
('JZTWFR', '若我不曾见过太阳', '知更鸟', '匿名', '崩铁', 'approved'),
('CX7A4W', '再度和你', '', '匿名', '', 'approved'),
('JQ7S0K', '星空列车与白的旅行OP Piano ver', '', '匿名', '动漫', 'approved'),
('T0MNQB', '肖邦降E大调夜曲', '', '匿名', '古典', 'approved'),
('J5XB2Z', '降临（绝区零二周年）', '', '匿名', '绝区零', 'approved'),
('4V5AM0', '初音未来的消失', '', '匿名', 'V家', 'approved'),
('UWAXDG', 'Rush E', '', '匿名', '经典', 'approved'),
('IN5JJF', '打上花火', '', '匿名', '动漫', 'approved'),
('2ZRE95', '乌吉恩圈bgm', '', '匿名', '游戏', 'approved'),
('CFQH1I', '莉奈娅PV 雨夜的同伴', '', '匿名', '', 'approved'),
('DNPLFE', '前前前世', '', '匿名', '动漫', 'approved'),
('6S83FD', '覆灭重生', '', '匿名', '', 'approved'),
('MTCL1V', 'DAMIDAMI', '', '匿名', '', 'approved'),
('WI8Z4E', '86Avid', '', '匿名', '动漫', 'approved'),
('RV144J', '游步欣愉', '', '匿名', '', 'approved'),
('TTKIBZ', '海滨小城', '', '匿名', '', 'approved'),
('TUYDYD', '飞鼠进行曲', '', '匿名', '', 'approved'),
('J5XB2Z', '预言prophecy', '', '匿名', '', 'approved'),
('N2GA4F', 'O叔版晴天', '', '匿名', '流行', 'approved'),
('G4O133', 'regression奥托印象曲', '', '匿名', '崩坏', 'approved'),
('UZYF3L', '千本樱', '', '匿名', 'V家', 'approved');
