-- ============================================================
-- 待收录榜（求谱）表 + RLS
-- 在 Supabase SQL Editor 中执行一次即可
-- ============================================================

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  title text not null,                 -- 想弹的曲名
  note text default '',                -- 补充说明（可选）
  votes integer default 0,             -- 求谱数
  status text default 'open',          -- open 待收录 / done 已收录
  created_at timestamptz default now()
);

-- 行级安全
alter table public.requests enable row level security;

-- 匿名可浏览
create policy "requests_select" on public.requests
  for select using (true);

-- 匿名可求谱（插入）
create policy "requests_insert" on public.requests
  for insert with check (true);

-- 匿名可点赞（更新 votes）—— 前端用 localStorage 做每设备去重
create policy "requests_update" on public.requests
  for update using (true) with check (true);
