-- ============================================================
-- 安全更新：举报 + 我的提交编辑（人工审核）
-- 在 Supabase SQL Editor 执行一次
-- ============================================================

-- 1) 提交编辑令牌列（提交时前端生成随机令牌存入）
alter table public.linli_codes add column if not exists submit_token text;

-- 2) 防刷举报日志表
create table if not exists public.report_log (
  id bigint generated by default as identity primary key,
  fp text not null,
  item_id bigint not null,
  created_at timestamptz default now()
);
alter table public.report_log enable row level security;

-- 3) 安全举报：只自增 reports，同一指纹 10 分钟限一次
create or replace function public.report_code(item_id bigint, fp text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.report_log
    where report_log.fp = report_code.fp
      and report_log.item_id = report_code.item_id
      and report_log.created_at > now() - interval '10 minutes'
  ) then
    update public.linli_codes set reports = coalesce(reports,0) + 1 where id = item_id;
    insert into public.report_log(fp, item_id) values (report_code.fp, report_code.item_id);
  end if;
end;
$$;

-- 4) 编辑审核表：编辑请求，不直接改线上数据
create table if not exists public.code_edits (
  id bigint generated by default as identity primary key,
  code_id bigint not null,
  submit_token text not null,
  old_title text, old_tags text, old_code text,
  new_title text, new_tags text, new_code text,
  reason text default '',                 -- 编辑理由
  status text default 'pending',          -- pending / applied / rejected
  created_at timestamptz default now()
);
alter table public.code_edits enable row level security;
create policy "code_edits_select" on public.code_edits for select using (true);

-- 5) 提交编辑申请：校验令牌归属 + 防重复待审，写 code_edits 不改 linli_codes
create or replace function public.submit_edit(item_id bigint, token text, title text, tags text, code text, reason text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  rec record;
begin
  select * into rec from public.linli_codes where id = item_id and submit_token = token;
  if rec.id is null then return false; end if;
  if exists (select 1 from public.code_edits where code_id = item_id and status = 'pending') then
    return false;
  end if;
  insert into public.code_edits(code_id, submit_token, old_title, old_tags, old_code, new_title, new_tags, new_code, reason)
  values (item_id, token, rec.title, rec.tags, rec.code, title, tags, code, coalesce(reason, ''));
  return true;
end;
$$;

-- 6) 管理员：应用编辑（只改 title/tags/code，不动 views/likes/status）
create or replace function public.apply_edit(edit_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  ed record;
begin
  select * into ed from public.code_edits where id = edit_id;
  if ed.id is null then return; end if;
  update public.linli_codes set title = ed.new_title, tags = ed.new_tags, code = ed.new_code where id = ed.code_id;
  update public.code_edits set status = 'applied' where id = edit_id;
end;
$$;

-- 7) 管理员：拒绝编辑
create or replace function public.reject_edit(edit_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.code_edits set status = 'rejected' where id = edit_id;
end;
$$;
