-- 待收录榜（求谱）表 + RLS
create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  title text not null,
  note text default '',
  votes integer default 0,
  status text default 'open',
  created_at timestamptz default now()
);

alter table public.requests enable row level security;

create policy "requests_select" on public.requests
  for select using (true);

create policy "requests_insert" on public.requests
  for insert with check (true);

create policy "requests_update" on public.requests
  for update using (true) with check (true);
